# #-------------------------------------------------------------------------------
# # Workflow configuration
# #-------------------------------------------------------------------------------

name: "Flatpak build"

on: workflow_dispatch
  
jobs:
  build-ios:
    runs-on: macos-latest
    defaults: 
      run:
        working-directory: blume-build

    steps:
      - name: (4) Check out code
        uses: actions/checkout@v3

      - name: (5) Set up Xcode environment
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: (6) Create build directory
        run: mkdir build
        # run: mkdir ${RUNNER_TEMP}/build

      - name: (7) Build with Xcode
        working-directory: build
        # working-directory: ${RUNNER_TEMP}/build
        run: |
          xcodebuild -project ${GITHUB_WORKSPACE}/Blume.xcodeproj -scheme Blume -sdk iphoneos -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: (8) Zip the build
        # working-directory: .
        # working-directory: ${RUNNER_TEMP}
        run: zip -r Blume-build.zip build/*

      - name: (9) Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Blume-Artifact
          path: build/Blume-build.zip
          # path: ${RUNNER_TEMP}/Blume-build.zip